spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coordinate
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

server:
  port: 8090
