INSERT INTO store(name, geolocation_id) VALUES('Farmacia Normal',6);
INSERT INTO store(name, geolocation_id) VALUES('Big Iguatemi',7);
INSERT INTO store(name, geolocation_id) VALUES('Angeloni Santa Monica',8);
INSERT INTO store(name, geolocation_id) VALUES('Mercado Carvoeira',9);
INSERT INTO store(name, geolocation_id) VALUES('Millium',10);
INSERT INTO store(name, geolocation_id) VALUES('Shopping via Lagoa',11);
INSERT INTO store(name, geolocation_id) VALUES('O Açougueiro',12);
INSERT INTO store(name, geolocation_id) VALUES('Lagoa Yatch Club',13);
INSERT INTO store(name, geolocation_id) VALUES('Pizza na Pedra',14);
INSERT INTO store(name, geolocation_id) VALUES('Supermercado Imperatriz',15);
INSERT INTO store(name, geolocation_id) VALUES('Bakery Manu',16);
INSERT INTO store(name, geolocation_id) VALUES('Bistek Supermercados',17);
INSERT INTO store(name, geolocation_id) VALUES('Ilha Sul Supermercados',18);
INSERT INTO store(name, geolocation_id) VALUES('Armazém Vieira',19);
INSERT INTO store(name, geolocation_id) VALUES('Francestar Panificadora',20);
INSERT INTO store(name, geolocation_id) VALUES('Dibi Mussi Pizzaria',21);
INSERT INTO store(name, geolocation_id) VALUES('McDonald''s',22);
INSERT INTO store(name, geolocation_id) VALUES('Restaurante Aladim',23);
INSERT INTO store(name, geolocation_id) VALUES('De Boa Lanchonete',24);
INSERT INTO store(name, geolocation_id) VALUES('Worlds Games',25);
INSERT INTO store(name, geolocation_id) VALUES('Vila do Divino',26);
INSERT INTO store(name, geolocation_id) VALUES('Angeloni Capoeiras',27);
INSERT INTO store(name, geolocation_id) VALUES('Ok Supermercados',28);
INSERT INTO store(name, geolocation_id) VALUES('Parma Pizzaria Capoeiras',29);
INSERT INTO store(name, geolocation_id) VALUES('Padaria Padre Roma',30);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT;
SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS;
SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION;
SET SQL_NOTES=@OLD_SQL_NOTES; 