INSERT INTO store(name, geolocation_id, city_id) VALUES('Farmacia Normal',6, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Big Iguatemi',7, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Angeloni Santa Monica',8, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Mercado Carvoeira',9, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Millium',10, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Shopping via Lagoa',11, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('O Açougueiro',12, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Lagoa Yatch Club',13, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Pizza na Pedra',14, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Supermercado Imperatriz',15, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Bakery Manu',16, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Bistek Supermercados',17, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Ilha Sul Supermercados',18, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Armazém Vieira',19, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Francestar Panificadora',20, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Dibi Mussi Pizzaria',21, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('McDonald''s',22, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Restaurante Aladim',23, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('De Boa Lanchonete',24, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Worlds Games',25, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Vila do Divino',26, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Angeloni Capoeiras',27, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Ok Supermercados',28, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Parma Pizzaria Capoeiras',29, 1);
INSERT INTO store(name, geolocation_id, city_id) VALUES('Padaria Padre Roma',30, 1);