INSERT INTO store(id, name, geolocation_id, city_id) VALUES(1 ,'Farmacia Normal',6, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(2 ,'Big Iguatemi',7, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(3 ,'Angeloni Santa Monica',8, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(4 ,'Mercado Carvoeira',9, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(5 ,'Millium',10, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(6 ,'Shopping via Lagoa',11, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(7 ,'O Açougueiro',12, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(8 ,'Lagoa Yatch Club',13, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(9 ,'Pizza na Pedra',14, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(10 ,'Supermercado Imperatriz',15, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(11 ,'Bakery Manu',16, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(12 ,'Bistek Supermercados',17, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(13 ,'Ilha Sul Supermercados',18, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(14 ,'Armazém Vieira',19, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(15 ,'Francestar Panificadora',20, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(16 ,'Dibi Mussi Pizzaria',21, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(17 ,'McDonald''s',22, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(18 ,'Restaurante Aladim',23, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(19 ,'De Boa Lanchonete',24, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(20 ,'Worlds Games',25, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(21 ,'Vila do Divino',26, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(22 ,'Angeloni Capoeiras',27, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(23 ,'Ok Supermercados',28, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(24 ,'Parma Pizzaria Capoeiras',29, 1);
INSERT INTO store(id, name, geolocation_id, city_id) VALUES(25 ,'Padaria Padre Roma',30, 1);